resource_group_name     = "TaskBoard"
resource_group_location = "North Europe"
app_service_plan_name   = "task-board-plan"
app_service_name        = "TaskBoardIvan"
sql_server_name         = "mssqlserver"
sql_database_name       = "TaskBoard"
sql_admin_name          = "user01"
sql_admin_password      = "thisIsKat11"
firewal_rule_name       = "FirewallRuleName"
repo_URL                = "https://github.com/PowerCell12/AzureWebAppSqlServerTerraform"

